### ISSUE TITLE
Disappearing page when scrolling from top to bottom and then bottom to top

### ISSUE THREAD

**Issue by fmniloyuk** [leemonade/leemons#54] opened 2023-07-18 17:09 UTC
Upon logging into the dashboard using a tutor account, I discovered a critical issue. When I scroll from the top of the page to the bottom and subsequently attempt to scroll back up from the bottom to the top, the entire page disappears. This behavior is unexpected and disrupts the usability of the platform.

Steps to reproduce the issue:
1. Log in to the dashboard using a tutor account.
2. Scroll down from the top of the page to the bottom.
3. Try scrolling back up from the bottom to the top.

At this point, the entire page disappears, leaving no content visible. Reloading the page is required to restore visibility.

This issue severely impacts the user experience and inhibits smooth navigation within the dashboard. It is essential to investigate and rectify this problem promptly, ensuring consistent visibility and reliable scrolling functionality throughout the platform.

https://www.loom.com/share/e857807f83834f3da1827b748fe69703?sid=056e7e52-2fb6-4bb3-af2a-259eb123bd76

**Comment by MIGUELez11** [comment] 2023-07-18 18:02
Hello 👋,

I can't reproduce this bug in any of our deployments, but it looks like the ongoing is failing to render the assignations for some reason and is throwing an error which ends in a full page failure.

Check the browser console to see if any error is thrown, and let me know please ☺.
Also, I'm planning on adding an Error Boundary to that component after several failures on it.

**Comment by fmniloyuk** [comment] 2023-07-19 08:26
Please check the attached screenshot. 

<img width="1435" alt="Screenshot 2023-07-19 at 2 25 28 PM" src="https://github.com/leemonade/leemons/assets/23031929/e11fbd33-0eda-47ea-b1a1-b8ed35c2055a">

**Comment by MIGUELez11** [comment] 2023-07-19 08:50
Looks like something is failing on the ongoing list, the .map error looks like is trying to iteare through the response without having it. I can't be sure if this can be fixed with the latests versions on dev

**Closed** 2023-07-29 15:16 UTC
