### ISSUE TITLE
Kanban feature not displaying assigned tasks in student account

### ISSUE THREAD

**Issue by fmniloyuk** [leemonade/leemons#42] opened 2023-05-22 08:28 UTC
I encountered an issue with the Kanban feature where assigned tasks are not being displayed in the student account. Here's what I did: 

1. Logged in as a tutor account.
2. Created a new task and assigned it to a student.
3. Expected the task to appear in the student's account under the Kanban board, but it does not show up.

This issue is hindering the workflow and collaboration between tutors and students. It would be greatly appreciated if this issue can be addressed and the Kanban feature can accurately display assigned tasks in the student accounts.

**Comment by MIGUELez11** [comment] 2023-05-22 09:53
After reviewing it with @fmniloyuk, we've seen that is a problema after an error during academic-tree student enrollment.

When you enroll a student into a class, it was throwing a success message followed by an error, this was produced by the same problem as issue #43. The user was being assigned to the class, but no permissions were being set.

The problem is not kanban, it was that the selected user was not the one he was looking into, because it does not appear in the list due to the previously described error.

After applying the #43 solution, we had to remove the user from the classes and enroll him again.

**Closed by MIGUELez11** 2023-05-22 09:53 UTC
