### ISSUE TITLE
Adding a new admin user after completing the initial setup fails

### ISSUE THREAD

**Issue by StarSheriff2** [leemonade/leemons#23] opened 2022-11-30 22:17 UTC
Bug: When attempting to add a new admin user, after the super user has completed the initial setup of the app, has logged out, and logs in again, doesn't work. The throws an error of `entry.notFound`.
When reading the server log, it appears that the backend attempts to edit existing users; that is, it attempts to _check_ if the users exist before editing/creating them.

Possible temporary workaround: Delete all users created in the initial setup. It should let you add new admin users again. (Haven't tested this thoroughly though)

Replicate bug:
### 1) Install the app with Docker on a Digital Ocean droplet with the following setup:
  - Droplet setup:
    - Ubuntu 18.04 (LTS) x64
    - 2 GB Memory
    - 2 AMD vCPUs
    - 60 GB Disk / SFO3
  - Install docker to the droplet:
    - Docker version 20.10.21, build baeda1f
  - Docker setup:
    - ./Docker-compose.yaml
  
```version: '3.8'
services:
   mysqldb:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
         MYSQL_DATABASE: $MYSQLDB_DATABASE
      ports:
         - $MYSQLDB_LOCAL_PORT:3306
      expose:
         - 3306
      volumes:
         - db:/var/lib/mysql
      healthcheck:
         test: mysqladmin ping -h 127.0.0.1 -uroot --password=$$MYSQL_ROOT_PASSWORD
         timeout: 10s
         retries: 10

   leemons:
      container_name: leemons
      image: leemonade/leemons:dev
      restart: always
      stdin_open: true
      tty: true
      expose:
         - 8080
      ports:
         - $NODE_LOCAL_PORT:8080
      environment:
         DATABASE_HOST: mysqldb
         DATABASE_PORT: 3306
         DATABASE_USERNAME: root
         DATABASE_DATABASE: $MYSQLDB_DATABASE
         DATABASE_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      depends_on:
         mysqldb:
            condition: service_healthy
   nginx:
      container_name: nginx-container #Proxy Server
      build: ./nginx
      expose:
         - 80
      links:
         - leemons
         - nginx-proxy
         - letsencrypt
      environment:
         - VIRTUAL_HOST=example.com
         - LETSENCRYPT_HOST=example.com
      volumes:
         - certs:/etc/nginx_certificate/certs:ro
      restart: always
   nginx-proxy:
      container_name: nginx-proxy
      image: jwilder/nginx-proxy
      restart: always
      ports:
         - '80:80'
         - '443:443'
      volumes:
         - /var/run/docker.sock:/tmp/docker.sock:ro
         - certs:/etc/nginx/certs:ro
         - vhostd:/etc/nginx/vhost.d
         - html:/usr/share/nginx/html
      labels:
         - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
   letsencrypt:
      image: jrcs/letsencrypt-nginx-proxy-companion
      restart: always
      environment:
         - NGINX_PROXY_CONTAINER=nginx-proxy
      volumes:
         - certs:/etc/nginx/certs:rw
         - /var/run/docker.sock:/var/run/docker.sock:ro
         - vhostd:/etc/nginx/vhost.d
         - html:/usr/share/nginx/html

volumes:
   db:
   certs:
   html:
   vhostd:
```
  - 
    - ./nginx/nginx.conf

```
events{
    worker_connections 768;
}
http{
    upstream backend {
        server leemons:8080;
    }

    upstream frontend {
        server leemons:8080;
    }
    
    server {
    listen 80;
    listen 443 default_server ssl;
    ssl_certificate /etc/nginx_certificate/certs/default.crt;
    ssl_certificate_key /etc/nginx_certificate/certs/default.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!MD5;
    server_name example.com;
    server_tokens off;
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri /index.html =404;

   

    location / {
        proxy_pass http://frontend;
    }

    location /api {
        proxy_pass http://backend;
    }

    }
```
  - 
    - ./nginx/Dockerfile
```
FROM nginx:alpine

RUN rm /etc/nginx/conf.d/*


COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
```
  - 
    - ./.env
```
MYSQLDB_USER=root
MYSQLDB_ROOT_PASSWORD=leemons
MYSQLDB_DATABASE=leemons
MYSQLDB_LOCAL_PORT=3307
NODE_LOCAL_PORT=8080
```
### 2) Install the app normally on a Macbook Pro M1 running Mac Os Ventura (Version 13.0.1 (22A400))
  - System env:
    - MySql 8.0.31
    - Python 3
    - Node v16.14.2
    - Yarn 1.22.19
  - Clone the leemons repo and checkout the "demo" branch
  - Follow installation instructions from the installation guide
  - Run the app as usual WITHOUT a data.xlsx file

### 3) Do following steps to replicate bug:
  - Follow the initial setup steps
    - Create at least one new admin user
  - Log out
  - Log in as a super user again
  - Try to add a new admin user
  - Expect to see an error with this message: **entry.notFound**

**Comment by MIGUELez11** [comment] 2022-11-30 22:36
Hi there!!

First of all, thanks for also reporting it through here.


I expect to be investigating this issue in the next 24 hours, I will notify when it's being investigated and if I can reproduce it. 

I'll try to release a fix, if not possible to have it fixed that fast, this fix will be inserted on the roadmap and notify here when it's fixed. 


Thanks for your collaboration ☺.

**Comment by MIGUELez11** [comment] 2022-12-01 13:44
Finally found it. It was hard 🥵 

## Temporal fix
I've found that @Cerberupo already fixed this issue at bb0ec53af26b229a85a1f807e78430f97e6e45b5. I've cherry-picked it to [demo](https://github.com/leemonade/leemons/tree/demo), so you don't have this problem anymore.

## Real fix
We are looking to update the [main](https://github.com/leemonade/leemons/tree/main) branch in the following days

> what does this mean?

It means you'll have new features and bug fixes, including this one, as it is already released on [dev](https://github.com/leemonade/leemons/tree/dev). This upload to main will also become with an updated docker build which currently uses the [main branch](https://github.com/leemonade/leemons/tree/main).

## Real solution for now without updating
The super-user view is only intended for the initial configuration, and no more use is expected after that; your admins should create other admins after that step. I know this only covers some of the use cases. That's why I'm releasing the hotfix.

## Steps to reproduce this bug
1. Setup the platform (including one admin)
2. Activate the admin and log in with that profile
3. Add a new user
4. Log out from the admin and log in as a super-user
5. Add a new admin
6. Expect the `entry.notFound` error being thrown.

**Closed by MIGUELez11** 2022-12-01 13:44 UTC

**Comment by StarSheriff2** [comment] 2022-12-01 15:13
Thank you for the quick help

**Comment by MIGUELez11** [comment] 2022-12-01 16:58
Maybe it's due to an old bug, which causes the very first backend init to not allow the admin to see some stuff.

Just restart the backend and they'll have full access.

This specific option is at `users > user list > top right corner add user`


PS: the hotfix is already uploaded to demo branch ☺

**Comment by StarSheriff2** [comment] 2022-12-01 20:04
Thank you @MIGUELez11 Your solution worked!
